backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  # - name: 'portfolio'
  #   label: 'Portfolio Page'
  #   folder: 'content/portfolio'
  #   create: true
  #   slug: 'portfolio'
  #   media_folder: ''
  #   public_folder: ''
  #   path: '{{title}}/portfolio'
  #   editor:
  #     preview: false
  #   fields:
  #       - { label: 'title', name: 'title', widget: 'string' }
  #       - { label: 'logo', name: 'logo', widget: 'image' }
  #       - { label: 'link', name: 'link', widget: 'string' }

  - name: 'about'
    label: 'About Page'
    files: 
        - label: 'Content'
          name: 'content'
          file: "site/content/about.json"
          fields:
            - { label: 'title', name: 'title', widget: 'string' , required: false}
            - { label: 'slug', name: 'slug', widget: 'string' , required: false}
            - { label: 'heading-one', name: 'heading-one', widget: 'text' , required: false}
            - { label: 'para-one', name: 'para-one', widget: 'text' , required: false}

            - { label: 'sub-heading-one', name: 'sub-heading-one', widget: 'text' , required: false}
            - { label: 'para-two', name: 'para-two', widget: 'text' , required: false}
            - { label: 'para-three', name: 'para-three', widget: 'text' , required: false}
            - { label: 'para-four', name: 'para-four', widget: 'text' , required: false}
            
            - { label: 'sub-heading-two', name: 'sub-heading-two', widget: 'text' , required: false}
            - { label: 'para-five', name: 'para-five', widget: 'text' , required: false}
            - { label: 'para-six', name: 'para-six', widget: 'text' , required: false}
            - { label: 'para-seven', name: 'para-seven', widget: 'text' , required: false}

            - { label: 'sub-heading-three', name: 'sub-heading-three', widget: 'text' , required: false}
            - { label: 'para-eight', name: 'para-eight', widget: 'text' , required: false}
            - { label: 'para-nine', name: 'para-nine', widget: 'text' , required: false}
            - { label: 'para-ten', name: 'para-ten', widget: 'text' , required: false}

            - { label: 'extras-one', name: 'extras-one', widget: 'text', required: false}
            - { label: 'extras-two', name: 'extras-two', widget: 'text', required: false}
            - { label: 'extras-three', name: 'extras-three', widget: 'text', required: false}
            
  - name: 'contact'
    label: 'Contact Page'
    files: 
        - label: 'Content'
          name: 'content'
          file: "site/content/contact.json"
          fields:
            - { label: 'title', name: 'title', widget: 'string' }
            - { label: 'slug', name: 'slug', widget: 'string' }
            - { label: 'heading-one', name: 'heading-one', widget: 'text' }
            - { label: 'para-one', name: 'para-one', widget: 'text' }
            - { label: 'heading-two', name: 'heading-two', widget: 'text' }
            - { label: 'para-two', name: 'para-two', widget: 'text' }

  - name: 'home'
    label: 'Home Page'
    files: 
        - label: 'Content'
          name: 'content'
          file: "site/content/home.json"
          fields:
            - { label: 'title', name: 'title', widget: 'string' }
            - { label: 'slug', name: 'slug', widget: 'string' }
            - { label: 'heading-one', name: 'heading-one', widget: 'text' }
            - { label: 'heading-one-strong', name: 'heading-one-strong', widget: 'text' }
            - { label: 'para-one', name: 'para-one', widget: 'text' }
            - { label: 'para-two', name: 'para-two', widget: 'text' }

  - name: 'details'
    label: 'Site Settings'
    files: 
        - label: 'Content'
          name: 'content'
          file: "site/content/settings.json"
          fields:
            - { label: 'linkedin', name: 'linkedin', widget: 'string' }
            - { label: 'twitter', name: 'twitter', widget: 'string' }
            - { label: 'github', name: 'github', widget: 'string' }
            - { label: 'email', name: 'email', widget: 'string' }
            - { label: 'address', name: 'address', widget: 'text' }
            - { label: 'jobs_link', name: 'jobs_link', widget: 'string' }
            - { label: 'footer_text', name: 'footer_text', widget: 'string' }